name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure gradlew is executable
      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build --quiet --stacktrace

      # Run tests with verbose output
      - name: Run tests
        run: ./gradlew test

      # Display test report for failures in logs
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results

      # Optional: Fail the job on test failure
      - name: Check and publish test results
        if: success() && (steps.test.outputs.result == 'success')
        run: |
          if ls build/test-results/test/*.xml 1> /dev/null 2>&1; then
            echo "Test results found. Publishing test results..."
            # Use the dorny/test-reporter action to publish the results
            uses: dorny/test-reporter@v3
            with:
              name: Gradle Tests
              path: build/test-results/test/*.xml
              reporter: java-junit
          else
            echo "No test results found"
            exit 1
          fi

#      - name: Publish Test Results
#        uses: dorny/test-reporter@v1
#        with:
#          name: Gradle Tests
#          path: build/test-results/test/*.xml
#          reporter: java-junit
