name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure gradlew is executable
      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build --info --stacktrace

      # Run tests with verbose output
      - name: Run tests
        run: ./gradlew test --info --stacktrace

      # Display test report for failures in logs
      - name: Display test report logs
        if: failure()
        run: |
          echo "Test Results:"
          cat build/test-results/test/*.xml || true
          echo "Test Report (HTML):"
          cat build/reports/tests/test/index.html || true

      # Upload test results as an artifact
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results/test
