name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Ensure gradlew is executable
      - name: Ensure gradlew is executable
        run: chmod +x gradlew

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Debug resources directory
          run: ls -R src/main/resources/

      # Build with Gradle
      - name: Build with Gradle
        run: ./gradlew clean build --quiet --stacktrace

      # Run tests with verbose output
      - name: Run tests
        run: ./gradlew test

      # Display test report for failures in logs
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: build/test-results

      # Optional: Fail the job on test failure
      - name: Check test results
        run: |
          if find build/test-results/test -name "*.xml" | grep -q .; then
            echo "Test results found"
          else
            echo "No test results found"
            exit 1
          fi
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:        # Name of the check run which will be created
          report_paths: 'build/test-results/test/*.xml'   # Path to test results
#      - name: Publish Test Results
#        uses: dorny/test-reporter@v1
#        with:
#          name: Gradle Tests
#          path: build/test-results/test/*.xml
#          reporter: java-junit
